// diallingCodes.jsx

import React from "react";
import { SelectItem } from "@/components/ui/select"; // Adjust the import path for SelectItem as needed

export const countries = [
  { code: "AF", name: "Afghanistan" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgium" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "BT", name: "Bhutan" },
  { code: "BO", name: "Bolivia" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BR", name: "Brazil" },
  { code: "BN", name: "Brunei" },
  { code: "BG", name: "Bulgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "CV", name: "Cabo Verde" },
  { code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" },
  { code: "CA", name: "Canada" },
  { code: "CF", name: "Central African Republic" },
  { code: "TD", name: "Chad" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CO", name: "Colombia" },
  { code: "KM", name: "Comoros" },
  { code: "CG", name: "Congo" },
  { code: "CD", name: "Congo (Democratic Republic)" },
  { code: "CR", name: "Costa Rica" },
  { code: "CI", name: "Côte d'Ivoire" },
  { code: "HR", name: "Croatia" },
  { code: "CU", name: "Cuba" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czech Republic" },
  { code: "DK", name: "Denmark" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "SV", name: "El Salvador" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "ER", name: "Eritrea" },
  { code: "EE", name: "Estonia" },
  { code: "SZ", name: "Eswatini" },
  { code: "ET", name: "Ethiopia" },
  { code: "FJ", name: "Fiji" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "France" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Germany" },
  { code: "GH", name: "Ghana" },
  { code: "GR", name: "Greece" },
  { code: "GD", name: "Grenada" },
  { code: "GT", name: "Guatemala" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "HN", name: "Honduras" },
  { code: "HU", name: "Hungary" },
  { code: "IS", name: "Iceland" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Iraq" },
  { code: "IE", name: "Ireland" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japan" },
  { code: "JO", name: "Jordan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KI", name: "Kiribati" },
  { code: "KP", name: "Korea (North)" },
  { code: "KR", name: "Korea (South)" },
  { code: "KW", name: "Kuwait" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "LA", name: "Laos" },
  { code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libya" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldives" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MH", name: "Marshall Islands" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "MX", name: "Mexico" },
  { code: "FM", name: "Micronesia" },
  { code: "MD", name: "Moldova" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolia" },
  { code: "ME", name: "Montenegro" },
  { code: "MA", name: "Morocco" },
  { code: "MZ", name: "Mozambique" },
  { code: "MM", name: "Myanmar" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "NL", name: "Netherlands" },
  { code: "NZ", name: "New Zealand" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "MK", name: "North Macedonia" },
  { code: "NO", name: "Norway" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palau" },
  { code: "PS", name: "Palestine" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" },
  { code: "QA", name: "Qatar" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russia" },
  { code: "RW", name: "Rwanda" },
  { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "LC", name: "Saint Lucia" },
  { code: "VC", name: "Saint Vincent and the Grenadines" },
  { code: "WS", name: "Samoa" },
  { code: "SM", name: "San Marino" },
  { code: "ST", name: "Sao Tome and Principe" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapore" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "South Africa" },
  { code: "SS", name: "South Sudan" },
  { code: "ES", name: "Spain" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SD", name: "Sudan" },
  { code: "SR", name: "Suriname" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "SY", name: "Syria" },
  { code: "TW", name: "Taiwan" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TH", name: "Thailand" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TG", name: "Togo" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Turkey" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TV", name: "Tuvalu" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "GB", name: "United Kingdom" },
  { code: "US", name: "United States" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VU", name: "Vanuatu" },
  { code: "VA", name: "Vatican City" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnam" },
  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
];

export const diallingCodes = [
  // Priority countries
  { key: "ZA", value: "+27", display: "+27 (ZA)" },
  { key: "GB", value: "+44", display: "+44 (GB)" },
  { key: "US", value: "+1", display: "+1 (US)" },

  // All other countries, sorted by dialling code
  { key: "AS", value: "+1", display: "+1 (AS)" },
  { key: "AI", value: "+1", display: "+1 (AI)" },
  { key: "AG", value: "+1", display: "+1 (AG)" },
  { key: "BS", value: "+1", display: "+1 (BS)" },
  { key: "BB", value: "+1", display: "+1 (BB)" },
  { key: "BM", value: "+1", display: "+1 (BM)" },
  { key: "VG", value: "+1", display: "+1 (VG)" },
  { key: "CA", value: "+1", display: "+1 (CA)" },
  { key: "KY", value: "+1", display: "+1 (KY)" },
  { key: "DM", value: "+1", display: "+1 (DM)" },
  { key: "DO", value: "+1", display: "+1 (DO)" },
  { key: "GD", value: "+1", display: "+1 (GD)" },
  { key: "GU", value: "+1", display: "+1 (GU)" },
  { key: "JM", value: "+1", display: "+1 (JM)" },
  { key: "MS", value: "+1", display: "+1 (MS)" },
  { key: "MP", value: "+1", display: "+1 (MP)" },
  { key: "PR", value: "+1", display: "+1 (PR)" },
  { key: "KN", value: "+1", display: "+1 (KN)" },
  { key: "LC", value: "+1", display: "+1 (LC)" },
  { key: "SX", value: "+1", display: "+1 (SX)" },
  { key: "VC", value: "+1", display: "+1 (VC)" },
  { key: "TT", value: "+1", display: "+1 (TT)" },
  { key: "TC", value: "+1", display: "+1 (TC)" },
  { key: "VI", value: "+1", display: "+1 (VI)" },
  { key: "RU", value: "+7", display: "+7 (RU)" },
  { key: "KZ", value: "+7", display: "+7 (KZ)" },
  { key: "EG", value: "+20", display: "+20 (EG)" },
  { key: "GR", value: "+30", display: "+30 (GR)" },
  { key: "NL", value: "+31", display: "+31 (NL)" },
  { key: "BE", value: "+32", display: "+32 (BE)" },
  { key: "FR", value: "+33", display: "+33 (FR)" },
  { key: "ES", value: "+34", display: "+34 (ES)" },
  { key: "HU", value: "+36", display: "+36 (HU)" },
  { key: "IT", value: "+39", display: "+39 (IT)" },
  { key: "RO", value: "+40", display: "+40 (RO)" },
  { key: "CH", value: "+41", display: "+41 (CH)" },
  { key: "AT", value: "+43", display: "+43 (AT)" },
  { key: "DK", value: "+45", display: "+45 (DK)" },
  { key: "SE", value: "+46", display: "+46 (SE)" },
  { key: "NO", value: "+47", display: "+47 (NO)" },
  { key: "SJ", value: "+47", display: "+47 (SJ)" },
  { key: "PL", value: "+48", display: "+48 (PL)" },
  { key: "DE", value: "+49", display: "+49 (DE)" },
  { key: "PE", value: "+51", display: "+51 (PE)" },
  { key: "MX", value: "+52", display: "+52 (MX)" },
  { key: "CU", value: "+53", display: "+53 (CU)" },
  { key: "AR", value: "+54", display: "+54 (AR)" },
  { key: "BR", value: "+55", display: "+55 (BR)" },
  { key: "CL", value: "+56", display: "+56 (CL)" },
  { key: "CO", value: "+57", display: "+57 (CO)" },
  { key: "VE", value: "+58", display: "+58 (VE)" },
  { key: "MY", value: "+60", display: "+60 (MY)" },
  { key: "AU", value: "+61", display: "+61 (AU)" },
  { key: "CX", value: "+61", display: "+61 (CX)" },
  { key: "CC", value: "+61", display: "+61 (CC)" },
  { key: "ID", value: "+62", display: "+62 (ID)" },
  { key: "PH", value: "+63", display: "+63 (PH)" },
  { key: "NZ", value: "+64", display: "+64 (NZ)" },
  { key: "PN", value: "+64", display: "+64 (PN)" },
  { key: "SG", value: "+65", display: "+65 (SG)" },
  { key: "TH", value: "+66", display: "+66 (TH)" },
  { key: "JP", value: "+81", display: "+81 (JP)" },
  { key: "KR", value: "+82", display: "+82 (KR)" },
  { key: "VN", value: "+84", display: "+84 (VN)" },
  { key: "CN", value: "+86", display: "+86 (CN)" },
  { key: "TR", value: "+90", display: "+90 (TR)" },
  { key: "IN", value: "+91", display: "+91 (IN)" },
  { key: "PK", value: "+92", display: "+92 (PK)" },
  { key: "AF", value: "+93", display: "+93 (AF)" },
  { key: "LK", value: "+94", display: "+94 (LK)" },
  { key: "MM", value: "+95", display: "+95 (MM)" },
  { key: "IR", value: "+98", display: "+98 (IR)" },
  { key: "SS", value: "+211", display: "+211 (SS)" },
  { key: "MA", value: "+212", display: "+212 (MA)" },
  { key: "DZ", value: "+213", display: "+213 (DZ)" },
  { key: "TN", value: "+216", display: "+216 (TN)" },
  { key: "LY", value: "+218", display: "+218 (LY)" },
  { key: "GM", value: "+220", display: "+220 (GM)" },
  { key: "SN", value: "+221", display: "+221 (SN)" },
  { key: "MR", value: "+222", display: "+222 (MR)" },
  { key: "ML", value: "+223", display: "+223 (ML)" },
  { key: "GN", value: "+224", display: "+224 (GN)" },
  { key: "CI", value: "+225", display: "+225 (CI)" },
  { key: "BF", value: "+226", display: "+226 (BF)" },
  { key: "NE", value: "+227", display: "+227 (NE)" },
  { key: "TG", value: "+228", display: "+228 (TG)" },
  { key: "BJ", value: "+229", display: "+229 (BJ)" },
  { key: "MU", value: "+230", display: "+230 (MU)" },
  { key: "LR", value: "+231", display: "+231 (LR)" },
  { key: "SL", value: "+232", display: "+232 (SL)" },
  { key: "GH", value: "+233", display: "+233 (GH)" },
  { key: "NG", value: "+234", display: "+234 (NG)" },
  { key: "TD", value: "+235", display: "+235 (TD)" },
  { key: "CF", value: "+236", display: "+236 (CF)" },
  { key: "CM", value: "+237", display: "+237 (CM)" },
  { key: "CV", value: "+238", display: "+238 (CV)" },
  { key: "ST", value: "+239", display: "+239 (ST)" },
  { key: "GQ", value: "+240", display: "+240 (GQ)" },
  { key: "GA", value: "+241", display: "+241 (GA)" },
  { key: "CG", value: "+242", display: "+242 (CG)" },
  { key: "CD", value: "+243", display: "+243 (CD)" },
  { key: "AO", value: "+244", display: "+244 (AO)" },
  { key: "GW", value: "+245", display: "+245 (GW)" },
  { key: "IO", value: "+246", display: "+246 (IO)" },
  { key: "AC", value: "+247", display: "+247 (AC)" },
  { key: "SC", value: "+248", display: "+248 (SC)" },
  { key: "SD", value: "+249", display: "+249 (SD)" },
  { key: "RW", value: "+250", display: "+250 (RW)" },
  { key: "ET", value: "+251", display: "+251 (ET)" },
  { key: "SO", value: "+252", display: "+252 (SO)" },
  { key: "DJ", value: "+253", display: "+253 (DJ)" },
  { key: "KE", value: "+254", display: "+254 (KE)" },
  { key: "TZ", value: "+255", display: "+255 (TZ)" },
  { key: "UG", value: "+256", display: "+256 (UG)" },
  { key: "BI", value: "+257", display: "+257 (BI)" },
  { key: "MZ", value: "+258", display: "+258 (MZ)" },
  { key: "ZM", value: "+260", display: "+260 (ZM)" },
  { key: "MG", value: "+261", display: "+261 (MG)" },
  { key: "RE", value: "+262", display: "+262 (RE)" },
  { key: "YT", value: "+262", display: "+262 (YT)" },
  { key: "ZW", value: "+263", display: "+263 (ZW)" },
  { key: "NA", value: "+264", display: "+264 (NA)" },
  { key: "MW", value: "+265", display: "+265 (MW)" },
  { key: "LS", value: "+266", display: "+266 (LS)" },
  { key: "BW", value: "+267", display: "+267 (BW)" },
  { key: "SZ", value: "+268", display: "+268 (SZ)" },
  { key: "KM", value: "+269", display: "+269 (KM)" },
  { key: "SH", value: "+290", display: "+290 (SH)" },
  { key: "ER", value: "+291", display: "+291 (ER)" },
  { key: "AW", value: "+297", display: "+297 (AW)" },
  { key: "FO", value: "+298", display: "+298 (FO)" },
  { key: "GL", value: "+299", display: "+299 (GL)" },
  { key: "GI", value: "+350", display: "+350 (GI)" },
  { key: "PT", value: "+351", display: "+351 (PT)" },
  { key: "LU", value: "+352", display: "+352 (LU)" },
  { key: "IE", value: "+353", display: "+353 (IE)" },
  { key: "IS", value: "+354", display: "+354 (IS)" },
  { key: "AL", value: "+355", display: "+355 (AL)" },
  { key: "MT", value: "+356", display: "+356 (MT)" },
  { key: "CY", value: "+357", display: "+357 (CY)" },
  { key: "FI", value: "+358", display: "+358 (FI)" },
  { key: "AX", value: "+358", display: "+358 (AX)" },
  { key: "BG", value: "+359", display: "+359 (BG)" },
  { key: "LT", value: "+370", display: "+370 (LT)" },
  { key: "LV", value: "+371", display: "+371 (LV)" },
  { key: "EE", value: "+372", display: "+372 (EE)" },
  { key: "MD", value: "+373", display: "+373 (MD)" },
  { key: "AM", value: "+374", display: "+374 (AM)" },
  { key: "BY", value: "+375", display: "+375 (BY)" },
  { key: "AD", value: "+376", display: "+376 (AD)" },
  { key: "MC", value: "+377", display: "+377 (MC)" },
  { key: "SM", value: "+378", display: "+378 (SM)" },
  { key: "UA", value: "+380", display: "+380 (UA)" },
  { key: "RS", value: "+381", display: "+381 (RS)" },
  { key: "ME", value: "+382", display: "+382 (ME)" },
  { key: "HR", value: "+385", display: "+385 (HR)" },
  { key: "SI", value: "+386", display: "+386 (SI)" },
  { key: "BA", value: "+387", display: "+387 (BA)" },
  { key: "MK", value: "+389", display: "+389 (MK)" },
  { key: "CZ", value: "+420", display: "+420 (CZ)" },
  { key: "SK", value: "+421", display: "+421 (SK)" },
  { key: "LI", value: "+423", display: "+423 (LI)" },
  { key: "FK", value: "+500", display: "+500 (FK)" },
  { key: "BZ", value: "+501", display: "+501 (BZ)" },
  { key: "GT", value: "+502", display: "+502 (GT)" },
  { key: "SV", value: "+503", display: "+503 (SV)" },
  { key: "HN", value: "+504", display: "+504 (HN)" },
  { key: "NI", value: "+505", display: "+505 (NI)" },
  { key: "CR", value: "+506", display: "+506 (CR)" },
  { key: "PA", value: "+507", display: "+507 (PA)" },
  { key: "PM", value: "+508", display: "+508 (PM)" },
  { key: "HT", value: "+509", display: "+509 (HT)" },
  { key: "GP", value: "+590", display: "+590 (GP)" },
  { key: "BL", value: "+590", display: "+590 (BL)" },
  { key: "MF", value: "+590", display: "+590 (MF)" },
  { key: "BO", value: "+591", display: "+591 (BO)" },
  { key: "GY", value: "+592", display: "+592 (GY)" },
  { key: "EC", value: "+593", display: "+593 (EC)" },
  { key: "GF", value: "+594", display: "+594 (GF)" },
  { key: "PY", value: "+595", display: "+595 (PY)" },
  { key: "MQ", value: "+596", display: "+596 (MQ)" },
  { key: "SR", value: "+597", display: "+597 (SR)" },
  { key: "UY", value: "+598", display: "+598 (UY)" },
  { key: "CW", value: "+599", display: "+599 (CW)" },
  { key: "TL", value: "+670", display: "+670 (TL)" },
  { key: "NF", value: "+672", display: "+672 (NF)" },
  { key: "BN", value: "+673", display: "+673 (BN)" },
  { key: "NR", value: "+674", display: "+674 (NR)" },
  { key: "PG", value: "+675", display: "+675 (PG)" },
  { key: "TO", value: "+676", display: "+676 (TO)" },
  { key: "SB", value: "+677", display: "+677 (SB)" },
  { key: "VU", value: "+678", display: "+678 (VU)" },
  { key: "FJ", value: "+679", display: "+679 (FJ)" },
  { key: "PW", value: "+680", display: "+680 (PW)" },
  { key: "WF", value: "+681", display: "+681 (WF)" },
  { key: "CK", value: "+682", display: "+682 (CK)" },
  { key: "NU", value: "+683", display: "+683 (NU)" },
  { key: "WS", value: "+685", display: "+685 (WS)" },
  { key: "KI", value: "+686", display: "+686 (KI)" },
  { key: "NC", value: "+687", display: "+687 (NC)" },
  { key: "TV", value: "+688", display: "+688 (TV)" },
  { key: "PF", value: "+689", display: "+689 (PF)" },
  { key: "TK", value: "+690", display: "+690 (TK)" },
  { key: "FM", value: "+691", display: "+691 (FM)" },
  { key: "MH", value: "+692", display: "+692 (MH)" },
  { key: "KP", value: "+850", display: "+850 (KP)" },
  { key: "HK", value: "+852", display: "+852 (HK)" },
  { key: "MO", value: "+853", display: "+853 (MO)" },
  { key: "KH", value: "+855", display: "+855 (KH)" },
  { key: "LA", value: "+856", display: "+856 (LA)" },
  { key: "XC", value: "+870", display: "+870 (XC)" },
  { key: "BD", value: "+880", display: "+880 (BD)" },
  { key: "TW", value: "+886", display: "+886 (TW)" },
  { key: "MV", value: "+960", display: "+960 (MV)" },
  { key: "LB", value: "+961", display: "+961 (LB)" },
  { key: "JO", value: "+962", display: "+962 (JO)" },
  { key: "SY", value: "+963", display: "+963 (SY)" },
  { key: "IQ", value: "+964", display: "+964 (IQ)" },
  { key: "KW", value: "+965", display: "+965 (KW)" },
  { key: "SA", value: "+966", display: "+966 (SA)" },
  { key: "YE", value: "+967", display: "+967 (YE)" },
  { key: "OM", value: "+968", display: "+968 (OM)" },
  { key: "PS", value: "+970", display: "+970 (PS)" },
  { key: "AE", value: "+971", display: "+971 (AE)" },
  { key: "IL", value: "+972", display: "+972 (IL)" },
  { key: "BH", value: "+973", display: "+973 (BH)" },
  { key: "QA", value: "+974", display: "+974 (QA)" },
  { key: "BT", value: "+975", display: "+975 (BT)" },
  { key: "MN", value: "+976", display: "+976 (MN)" },
  { key: "NP", value: "+977", display: "+977 (NP)" },
  { key: "TJ", value: "+992", display: "+992 (TJ)" },
  { key: "TM", value: "+993", display: "+993 (TM)" },
  { key: "AZ", value: "+994", display: "+994 (AZ)" },
  { key: "GE", value: "+995", display: "+995 (GE)" },
  { key: "KG", value: "+996", display: "+996 (KG)" },
  { key: "UZ", value: "+998", display: "+998 (UZ)" },
];
